services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    network_mode: host
    environment:
      POSTGRES_DB: "disable"
      POSTGRES_USER: &PGUSER "postgres"
      POSTGRES_PASSWORD: &PGPASSWORD "password"
      PGSSLMODE: "disable"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  integresql:
    image: ghcr.io/allaboutapps/integresql:v1.1.0
    network_mode: host
    depends_on:
      - postgres
    environment: 
      PGHOST: "localhost"
      PGUSER: *PGUSER
      PGPASSWORD: *PGPASSWORD

volumes:
  pgvolume:
